version: '3.8'

services:
  grace-core:
    build:
      context: ./grace_core
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=grace
      - POSTGRES_PASSWORD=gracepass
      - POSTGRES_DB=grace_os
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
